#!/bin/bash

source ./env.sh

curl -L ${ISO_URL} -o ${ISO_FN}
curl -L ${FRTCP_URL} -o ${FRTCP_FN}
curl -L ${LNCR_URL} -o ${LNCR_ZIP}

unzip ${LNCR_ZIP} ${LNCR_FN}

mkdir isofs
mount -t iso9660 -o loop,ro ${ISO_FN} isofs
unsquashfs -d rootfs ./isofs/artix/${ARCH}/rootfs.sfs

mount --bind rootfs rootfs
mount -t proc none rootfs/proc
mount -t sysfs none rootfs/sys
mount -o bind /dev rootfs/dev
mount -o bind /dev/pts rootfs/dev/pts

echo "LANG=en_US.UTF-8" >> rootfs/etc/locale.conf
sed -i -e "s/#en_US.UTF-8/en_US.UTF-8/" rootfs/etc/locale.gen
sed -i -e "s/#IgnorePkg   =/IgnorePkg   = fakeroot/" rootfs/etc/pacman.conf
cp ${FRTCP_FN} rootfs/root/

cat <<EOF | chroot rootfs /bin/sh -
locale-gen
pacman -U /root/${FRTCP_FN} --noconfirm
EOF

echo "# This file was automatically generated by WSL. \
To stop automatic generation of this file, remove this line." > rootfs/etc/resolv.conf
rm -f rootfs/root/${FRTCP_FN}

umount rootfs/dev/pts
umount rootfs/dev
umount rootfs/sys
umount rootfs/proc
umount rootfs

tar zcpf rootfs.tar.gz -C rootfs .
mv ${LNCR_FN} Artix.exe
zip Artix.zip Artix.exe rootfs.tar.gz
